### ISSUE TITLE
AttributeError: 'BiScaler' object has no attribute 'complete'

### ISSUE THREAD

**Issue by vjancik** [hammerlab/fancyimpute#11]
Your BiScaler class is missing the `Solver.__init__` call in it's constructor so it doesn't inherit the `complete` method. Is this a bug? If not how should the BiScaler class be used?
https://github.com/hammerlab/fancyimpute/blob/master/fancyimpute/biscaler.py#L27

**Comment by sergeyf** [comment]
Howdy,

BiScaler is not a matrix completion algorithm. It's a pre-processing step. So it does have fit and fit_transform.

Check out section 8 (page 30) of: https://arxiv.org/pdf/1410.2596.pdf
