### ISSUE TITLE
Rank and MAE are both increasing for SoftImpute

### ISSUE THREAD

**Issue by aburkov** [hammerlab/fancyimpute#15]
Starting from Iter 13 both rank and MAE are increasing.

[SoftImpute] Max Singular Value of X_init = 1345.871031
[SoftImpute] Iter 1: observed MAE=0.002085 rank=2000
[SoftImpute] Iter 2: observed MAE=0.002495 rank=2000
[SoftImpute] Iter 3: observed MAE=0.002674 rank=1994
[SoftImpute] Iter 4: observed MAE=0.002806 rank=1977
[SoftImpute] Iter 5: observed MAE=0.002879 rank=1959
[SoftImpute] Iter 6: observed MAE=0.002915 rank=1943
[SoftImpute] Iter 7: observed MAE=0.002932 rank=1924
[SoftImpute] Iter 8: observed MAE=0.002943 rank=1909
[SoftImpute] Iter 9: observed MAE=0.002951 rank=1899
[SoftImpute] Iter 10: observed MAE=0.002960 rank=1891
[SoftImpute] Iter 11: observed MAE=0.002969 rank=1887
[SoftImpute] Iter 12: observed MAE=0.002977 rank=1884
[SoftImpute] Iter 13: observed MAE=0.002984 rank=1884
[SoftImpute] Iter 14: observed MAE=0.002991 rank=1883
[SoftImpute] Iter 15: observed MAE=0.002998 rank=1884
[SoftImpute] Iter 16: observed MAE=0.003003 rank=1887
[SoftImpute] Iter 17: observed MAE=0.003008 rank=1889
[SoftImpute] Iter 18: observed MAE=0.003012 rank=1892
[SoftImpute] Iter 19: observed MAE=0.003015 rank=1896
[SoftImpute] Iter 20: observed MAE=0.003019 rank=1897
[SoftImpute] Iter 21: observed MAE=0.003022 rank=1900
[SoftImpute] Iter 22: observed MAE=0.003024 rank=1903
[SoftImpute] Iter 23: observed MAE=0.003027 rank=1906
[SoftImpute] Iter 24: observed MAE=0.003029 rank=1908
[SoftImpute] Iter 25: observed MAE=0.003031 rank=1911
[SoftImpute] Iter 26: observed MAE=0.003033 rank=1912
[SoftImpute] Iter 27: observed MAE=0.003035 rank=1915
[SoftImpute] Iter 28: observed MAE=0.003037 rank=1916
[SoftImpute] Iter 29: observed MAE=0.003038 rank=1917
[SoftImpute] Iter 30: observed MAE=0.003040 rank=1919
[SoftImpute] Iter 31: observed MAE=0.003042 rank=1922
[SoftImpute] Iter 32: observed MAE=0.003043 rank=1923
[SoftImpute] Iter 33: observed MAE=0.003045 rank=1924
[SoftImpute] Iter 34: observed MAE=0.003046 rank=1925
[SoftImpute] Iter 35: observed MAE=0.003047 rank=1926
[SoftImpute] Iter 36: observed MAE=0.003049 rank=1927
[SoftImpute] Iter 37: observed MAE=0.003050 rank=1928
[SoftImpute] Iter 38: observed MAE=0.003051 rank=1929
[SoftImpute] Iter 39: observed MAE=0.003052 rank=1930
[SoftImpute] Iter 40: observed MAE=0.003054 rank=1932
[SoftImpute] Iter 41: observed MAE=0.003055 rank=1933
[SoftImpute] Iter 42: observed MAE=0.003056 rank=1934
[SoftImpute] Iter 43: observed MAE=0.003057 rank=1934
[SoftImpute] Iter 44: observed MAE=0.003058 rank=1935
[SoftImpute] Iter 45: observed MAE=0.003059 rank=1937
[SoftImpute] Iter 46: observed MAE=0.003060 rank=1937

Used parameters:

fancyimpute.SoftImpute(shrinkage_value=2, init_fill_method="random",min_value = 0.0, max_value=200.0, max_iters=100)

**Comment by sergeyf** [comment]
@aburkov Are you able to share the data that this happens on?

@iskandr Any ideas? This seems pretty wacky.

**Comment by iskandr** [comment]
Hard to tell what's going on without example data. However, it's not impossible for rank to go back up before coming down again, I don't think there are guarantees on the individual iterations.

**Comment by iskandr** [comment]
Hey @aburkov, let us know if you can send us example data for this problem. Closing for now.
