### ISSUE TITLE
Installation issue in Windows (Python 2.7)

### ISSUE THREAD

**Issue by Iceman121** [hammerlab/fancyimpute#16]
I'm trying to install fancyimpute in Windows 8.1, Anaconda 2.4.1, Python 2.7.12. But when I try to import it (both on terminal and Spyder environments), I get the error "No module named _multiprocess". I do have multiprocess installed on my system. Any help on this would be great. Please let me know if you need any more information.

Thanks.

**Comment by sergeyf** [comment]
I also have Windows, and this kind of stuff is frustrating. Probably your C++ environment is not exactly what's required. See here: https://github.com/uqfoundation/multiprocess/issues/10

**Comment by Iceman121** [comment]
Hey, I followed all the steps, except downloading miniconda (I am already using anaconda). I rebooted my machine post installation but still stuck with the error of _multiprocessing. I tried calling "from fancyimpute import BitScaler" from Spyder IDE and cmd prompt, but received the same error in both places.

**Comment by sergeyf** [comment]
Hmm, not sure then. This is an issue that lies outside of our package. Do let us know if you figure out a solution.

**Comment by Iceman121** [comment]
Resolved. I rebuilt multiprocess from https://github.com/uqfoundation/multiprocess. fancyimpute is working fine now. Thanks for your input!

**Comment by sergeyf** [comment]
Glad to hear it is working! Windows is a bit of a nightmare =)

**Comment by erseema** [comment]
@Iceman121  could you please elaborate process of installing fancyimpute on windows 10.
I tried using pip but it fails to build.

**Comment by Iceman121** [comment]
Hi @erseema, pip should work if you have gcc installed on your system. Do you?

**Comment by erseema** [comment]
Hi @Iceman121  , i hvnt installed gcc. 
I first installed cvxpy and then  installed fancyimpute .. Though its showing requirement satisfied and I can see fancyimpute package available in Anaconda\lib\site-package .. but not able to import in notebook

**Comment by Iceman121** [comment]
Can you please try the following and post the error messages you are getting:
1. In command window, 
```
python -c "import fancyimpute"
python -c "import theano"
```
2. In Notebook,
```
import fancyimpute
```
3. Post your notebook version
4. Post your Python version

Thanks!

**Comment by erseema** [comment]
@Iceman121  ,I don't know how it happened, but it worked,,
:)
Thanks
