### ISSUE TITLE
Versions of libs in requirements.txt

### ISSUE THREAD

**Issue by stripathi669** [hammerlab/fancyimpute#17]
Please mention the exact version of libs in requirements.txt.

Latest version of Cvpxy is giving error due as it has moved ahead of version you used.

**Comment by brettbj** [comment]
@stripathi669  I had to go back to version - v0.2.28 to get it to work

**Comment by iskandr** [comment]
Hey @brettbj & @stripathi669 which error do you get? We should probably just fix fancyimpute to work with the latest lib.
