### ISSUE TITLE
Issue with autoencoder

### ISSUE THREAD

**Issue by mbahri** [hammerlab/fancyimpute#19]
Hi

I would like to report an issue with the AutoEncoder imputer.

Platform: Python 3.5 via Anaconda. Keras with TensorFlow backend on Mac OS 10.11.6

Error message:

> Hidden layer sizes: [2000, 500, 1504]
> Traceback (most recent call last):
> 
>   File "<ipython-input-145-1bcabef679cf>", line 1, in <module>
>     X_filled_ae = fi.AutoEncoder().complete(M)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/solver.py", line 207, in complete
>     imputations = self.multiple_imputations(X)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/solver.py", line 199, in multiple_imputations
>     return [self.single_imputation(X) for _ in range(self.n_imputations)]
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/solver.py", line 199, in <listcomp>
>     return [self.single_imputation(X) for _ in range(self.n_imputations)]
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/solver.py", line 184, in single_imputation
>     X_result = self.solve(X_filled, missing_mask)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/auto_encoder.py", line 140, in solve
>     self.network = self._create_fresh_network(n_features)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/auto_encoder.py", line 91, in _create_fresh_network
>     optimizer=self.optimizer)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/neuralnet_helpers.py", line 94, in make_network
>     nn.compile(optimizer=optimizer, loss=loss_function)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/keras/models.py", line 553, in compile
>     **kwargs)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 630, in compile
>     sample_weight, mask)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 332, in weighted
>     score_array = fn(y_true, y_pred)
> 
>   File "/Users/<username>/anaconda3/lib/python3.5/site-packages/fancyimpute/neuralnet_helpers.py", line 26, in reconstruction_loss
>     X_values.name = "$X_values"
> 
> AttributeError: can't set attribute

Many thanks

**Comment by iskandr** [comment]
Looks like we're assuming a Theano backend. We'll look at how to set names in a backend agnostic fashion.

**Comment by mbahri** [comment]
I confirm it works as expected with Theano. Let me know if there is anything I can do to help.

**Comment by iskandr** [comment]
@mbahri Have you found the AutoEncoder useful? We're discussing getting rid of it.

**Comment by mbahri** [comment]
@iskandr Unfortunately I haven't been able to test it due to lack of suitable hardware at work (and at home too for that matter), training is impractical without a GPU.

I've seen someone asking for a reference paper on another issue, they seem to have some use of it.

**Comment by LeandroRitter** [comment]
Hi guys,

has autoencoder been removed from fancyimpute? I can't find any codes and would love to use it for data imputation. Would it still be posdible to share the autoencoder codes? Thanks!

**Comment by sergeyf** [comment]
It is gone, yes. We had lots of issues with it, and it never worked well. You can find the replaced code via this PR: https://github.com/hammerlab/fancyimpute/pull/27

**Comment by LeandroRitter** [comment]
Thanks Sergey! Where exactly can I find the replaced code?

Sent from my iPhone

On 28 Dec 2017, at 22:38, Sergey Feldman <notifications@github.com<mailto:notifications@github.com>> wrote:


It is gone, yes. We had lots of issues with it, and it never worked well. You can find the replaced code via this PR: #27<https://github.com/hammerlab/fancyimpute/pull/27>

**Comment by sergeyf** [comment]
Not exactly easy to work with, but the left-hand column here
https://github.com/hammerlab/fancyimpute/pull/27/files

You'll see which functions were excised.
