### ISSUE TITLE
Reference(s) for the Autoencoder implementation

### ISSUE THREAD

**Issue by curiousily** [hammerlab/fancyimpute#23]
Hi,

All (or most) of the algorithms have reference papers associated with them. Can you provide some references for the AutoEncoder implementation?

Thank you for creating such a cool library!

**Comment by iskandr** [comment]
Glad you find it useful! The AutoEncoder was an experiment that @sergeyf and I cooked up at NIPS last year and I don't think it's ever been that successful. I'm considering getting rid of it to lighten the dependencies. Thoughts?

**Comment by sergeyf** [comment]
I vote for ditching it. Neural networks are too fragile.

**Comment by iskandr** [comment]
Cool, on it!

**Comment by iskandr** [comment]
What about the MatrixFactorization with DownHill? It's pretty slow, not sure if it's useful.

**Comment by sergeyf** [comment]
Yeah, good question. There are probably good alternatives for this out there? It's just SVD with SGD, right?

**Comment by sergeyf** [comment]
BTW, the latest master of scikit-learn has linear models that can produce posteriors, but we can't require that until the next version actually comes out. Then the code will be even cleaner

**Comment by iskandr** [comment]
Awesome. That was your addition, right?

If we are happy with just a few imputation methods, we could probably just
move everything over to sklearn.

**Comment by sergeyf** [comment]
Yes that was me.

That's probably best for "society". I was a little daunted by all the style and documentation requirements. Other than that I already have a pull request of basic MICE for sklearn ready, but have been putting off finishing it.

**Comment by mbahri** [comment]
I'm using the MatrixFactorization with Downhill and find it to be the best (among the methods implemented in fancyimpute) for some applications, but perhaps faster options are available elsewhere? The stochastic optimization algorithm seems a bit overkill for my use and I would rather have faster convergence.
