### ISSUE TITLE
Got TypeError when trying imputing a Pandas DataFrame

### ISSUE THREAD

**Issue by jiyuan312986471** [hammerlab/fancyimpute#24]
Hi everyone,

I'm trying to use MICE on a pandas dataframe:
```
from fancyimpute import MICE
MICE(n_imputations=np.infty).complete(df)
```
But got `TypeError`:
```
TypeErrorTraceback (most recent call last)
<ipython-input-17-c1a653d27988> in <module>()
      1 # Impute AGE_CLI with MICE
      2 from fancyimpute import MICE
----> 3 MICE(n_imputations=np.infty).complete(df)

/usr/local/lib/python3.4/dist-packages/fancyimpute/mice.py in complete(self, X)
    332             print("[MICE] Completing matrix with shape %s" % (X.shape,))
    333         X_completed = X.copy()
--> 334         imputed_arrays, missing_mask = self.multiple_imputations(X)
    335         # average the imputed values for each feature
    336         average_imputated_values = imputed_arrays.mean(axis=0)

/usr/local/lib/python3.4/dist-packages/fancyimpute/mice.py in multiple_imputations(self, X)
    293         X = np.asarray(X)
    294         self._check_input(X)
--> 295         missing_mask = np.isnan(X)
    296         self._check_missing_value_mask(missing_mask)
    297 

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

```
After a brief searching, I found that 

> [`np.isnan` can be applied to NumPy arrays of native dtype but raises TypeError when applied to object arrays](http://stackoverflow.com/questions/36000993/numpy-isnan-fails-on-an-array-of-floats-from-pandas-dataframe-apply)

How could I use fancyimpute with pandas dataframe ?

**Comment by sergeyf** [comment]
Just do `np.array(X)` and it will work fine. We don't support `pd.DataFrame`.

**Comment by jiyuan312986471** [comment]
`np.array(X)` doesn't work neither

**Comment by jiyuan312986471** [comment]
it was my bad, i shouldn't use `np.inf` as `n_imputations`, thx for helping

**Comment by pancho111203** [comment]
Still not working for me, and I tried with np.array()
`filled_applications = MICE(n_imputations=100).complete(np.array(previous_applications))`

> TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
