### ISSUE TITLE
make dependencies optional

### ISSUE THREAD

**Issue by DeoLeung** [hammerlab/fancyimpute#25]
Hi,

thanks for the great module

it will be great that if the dependencies can be optional.

for example, if I just use knn, I would like to not have `keras`, `theano` installed

using technique like:
```sh
pip install fancyimpute[knn]
```

**Comment by iskandr** [comment]
I'm considering getting rid of the AutoEncoder since it was experimental and never worked that well. If I ditch keras and its dependencies, are you OK with the remainder?

**Comment by DeoLeung** [comment]
That will be great.

**Comment by iskandr** [comment]
Getting rid of AutoEncoder eliminates keras as a dependency but still leaves Theano (since it's required for MatrixFactorization). Is that enough?

**Comment by DeoLeung** [comment]
Thanks, looks good so far, hope it's available on `Pypi` soon

for future record, `Theano` requires the python binary built with `--enable-shared`

**Comment by DeoLeung** [comment]
@iskandr any plan to upload `0.2.0` to `pypi`?

also, here is an example for optional install
```python

# setup.py

        install_requires=[
            'six',
            'numpy>=1.10'
        ],
        extras_require={
            'knn': ['knnimpute'],
            # need at least 1.10 for np.multi_dot
            'all': ['scipy',
                    # used by NuclearNormMinimization
                    'cvxpy',
                    'scikit-learn>=0.17.1',
                    # used by MatrixFactorization
                    'downhill',
                    'climate',
                    'theano']
```

will be good to add in

**Comment by iskandr** [comment]
@DeoLeung  Sorry for the delay, its on PyPI. 

(thanks for the optional deps example)
