### ISSUE TITLE
Applying to new data

### ISSUE THREAD

**Issue by amueller** [hammerlab/fancyimpute#26]
Is there a way to apply an imputation model to new data without reestimating the model?

In a supervised setting you don't want to retrain your whole model every time you see a new test instance.

Thanks.

**Comment by sergeyf** [comment]
Not at the moment. I have a version of MICE that stores all of the `n_imputation` models made during `fit`, and then just applies them in the same order at `predict`. No time right now to get it into the codebase, sadly. And I am not sure how well this generalizes to the other methods.

**Comment by amueller** [comment]
Fair enough. I was hoping I was just missing something.
Might fit better with scikit-learn - we'll just steal all your cool stuff for which we can implement transform.

**Comment by sergeyf** [comment]
I agree. My implementation of basic MICE for sklearn is pretty much done, it just needs two things:

(1) An implementation of probabilistic mean matching.
(2) A lot of documentation.

I got super busy, so not sure when I'll have time to actually finish it. I can toss up a half-finished version if that is helpful.

**Comment by amueller** [comment]
maybe. I'm also too busy to do anything useful right now :-/

**Comment by sergeyf** [comment]
Sounds like we're both cursed in the same way =)

**Comment by iskandr** [comment]
I can imagine trying to incrementalize KNN to work for new samples but you'd have to keep around the original dataset and compute distances of new samples to that stored data. For MICE, I guess we can keep the completed dataset, combine it with the new incomplete samples, and then run more iterations. Probably every method is amenable to that kind of "keep the data" approach -- but I suspect that's not going to be fast/efficient enough for many cases. 

@sergeyf can you think of an imputation algorithm which can use just the models/parameters learned from one datasets to complete another?

**Comment by sergeyf** [comment]
For MICE, you don't need to keep the original dataset. You just need to keep each of the `n_imputations * d` models around.

**Comment by iskandr** [comment]
Ah, you're right!

**Comment by sergeyf** [comment]
I think it's the best candidate for the sklearn API.

**Comment by amueller** [comment]
We definitely also want to KNN - memorizing all the data is standard for knn things. We have a PR but that's kinda stalled.

**Comment by sergeyf** [comment]
@iskandr there is a MICE pull request up on sklearn https://github.com/scikit-learn/scikit-learn/pull/8465

It could use some tests if you have some time to help =)

**Comment by sergeyf** [comment]
The MICE PR is pretty much done and waiting for comments. I'm closing this for now.
