### ISSUE TITLE
KNN implemenation reference paper

### ISSUE THREAD

**Issue by shyamkkhadka** [hammerlab/fancyimpute#31]
Hi, 
All the methods have reference paper, except KNN method. Could you please provide reference paper for KNN also ?

**Comment by sergeyf** [comment]
I think Alex kinda made it up, right @iskandr?

**Comment by iskandr** [comment]
Yeah, that's pretty much right. It's inspired by the R implementation of knnImpute, which I think I've more or less reimplemented.

**Comment by sergeyf** [comment]
I'll stick `Inspired by the R Implementation of knnImpute` in the docstring of `knn`. Thanks!
