### ISSUE TITLE
[KNN] Warning: 240/480 still missing after imputation, replacing with 0

### ISSUE THREAD

**Issue by Make42** [hammerlab/fancyimpute#32]
I get the message

    [KNN] Warning: 240/480 still missing after imputation, replacing with 0

What is the background that KNN was not able to impute? How can I solve this issue?

**Comment by sergeyf** [comment]
kNN uses a distance that takes into account only those features/dimensions/variables where both vectors have values. It might be the case that some never get filled because of this. So it just fills it in with zeros. It's just a part of the algorithm.
