### ISSUE TITLE
how to use knn with Biscale?

### ISSUE THREAD

**Issue by luofanghao** [hammerlab/fancyimpute#33]
according to the knn code there is a parameter "normalizer". And says it could be object like Biscale. But when I do this:
`data_clean = KNN(k=5, normalizer=BiScaler).complete(data) `

the error below occurred:
`File "/usr/local/lib/python2.7/site-packages/fancyimpute/solver.py", line 207, in complete
    imputations = self.multiple_imputations(X)                                           
  File "/usr/local/lib/python2.7/site-packages/fancyimpute/solver.py", line 199, in multiple_imputations
    return [self.single_imputation(X) for _ in range(self.n_imputations)]                
  File "/usr/local/lib/python2.7/site-packages/fancyimpute/solver.py", line 176, in single_imputation
    X = self.normalizer.fit_transform(X)    
TypeError: unbound method fit_transform() must be called with BiScaler instance as first argument (got ndarray instance instead)`

**Comment by KhaledTo** [comment]
You probably just need to instantiate  BiScaler.

**Comment by luofanghao** [comment]
Oh sorry I did not notice that. Thank you so much
