### ISSUE TITLE
can we speed up using GPU

### ISSUE THREAD

**Issue by bicepjai** [hammerlab/fancyimpute#34]
can we use this library with GPU ?
If so is there a setup process ?

**Comment by iskandr** [comment]
All of the code, so far, is written using pure NumPy operations that won't benefit from a GPU. It's imaginable that some of the algorithms could get ported to use Theano or TensorFlow but I don't think that either @sergeyf or I have time for that. Want to add GPU acceleration for a particular algorithm as an issue? Maybe someone else will pick it up.
