### ISSUE TITLE
RuntimeError: Numpy version during compilation is different from local numpy version

### ISSUE THREAD

**Issue by sgokhales** [hammerlab/fancyimpute#43]
Hello,

I've installed `fancyimpute` on my local system using `pip install fancyimpute`. When I try to import the package in my jupyter notebook, I encounter below error. 

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
> 
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> D:\Anaconda3\envs\dlwin36\lib\site-packages\theano\gof\cutils.py in <module>()
>     305     try:
> --> 306         from cutils_ext.cutils_ext import *  # noqa
>     307     except ImportError:
> 
> ImportError: numpy.core.multiarray failed to import
> 
> During handling of the above exception, another exception occurred:
> 
> RuntimeError                              Traceback (most recent call last)
> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

Things that I've already tried:
* Run `conda update --all` to update all anaconda packages to their latest version
* Uninstall `numpy` and re-install it.

Both the workaround didn't work.

Any suggestions?

**Comment by sergeyf** [comment]
Try this:

`import numpy as np` - does it work? If not, it's your numpy install.
`import theano` - does it work? If not, it's your theano install. We're working on getting rid of `theano` dependency, but it'll probably take until at least end of the year.

**Comment by sgokhales** [comment]
Thanks for your recommendation, but the issue is fixed now. I had to update my `numpy` to the latest version using `pip install numpy --upgrade`. 

The error was occurring earlier due to the fact that I was unable to update `numpy` while running `jupyter` notebook under `anaconda` environment.

**Comment by sergeyf** [comment]
Excellent!
