### ISSUE TITLE
GFORTRAN_1.4' not found (required by /usr/lib/liblapack.so.3)

### ISSUE THREAD

**Issue by birdmw** [hammerlab/fancyimpute#8]
from fancyimpute import KNN

results in:

ImportError: /home/user/anaconda2/lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/liblapack.so.3)

**Comment by sergeyf** [comment]
Hmm, not sure what this could be - our lapack is borked? Which line fails exactly?

**Comment by birdmw** [comment]
ill check when i get home in a couple hrs
On Apr 27, 2016 5:54 PM, "Sergey Feldman" <notifications@github.com> wrote:
>
> Hmm, not sure what this could be - our lapack is borked? Which line fails
exactly?

**Comment by iskandr** [comment]
Hey @birdmw, did you figure this out?

**Comment by timodonnell** [comment]
Also hit this, was able to use the workaround given here: https://github.com/ContinuumIO/anaconda-issues/issues/686

```
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
```

**Comment by iskandr** [comment]
Thanks @timodonnell!
