### ISSUE TITLE
Issue in pip install

### ISSUE THREAD

**Issue by zeeshansayyed** [hammerlab/fancyimpute#9]
I installed fancyimpute from pip. But there seems to be some issue with it when I import it. Also, when I cloned the repo and used the setup.py to install it, this issue didn't exit.

`from fancyimpute import KNN`

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-809ce37da21f> in <module>()
> ----> 1 from fancyimpute import KNN
> 
> /Users/zeeshan.sayyed/anaconda/lib/python2.7/site-packages/fancyimpute/__init__.py in <module>()
>       4 from .nuclear_norm_minimization import NuclearNormMinimization
>       5 from .bayesian_ridge_regression import BayesianRidgeRegression
> ----> 6 from .mice import MICE
>       7 from .auto_encoder import AutoEncoder
>       8 from .matrix_factorization import MatrixFactorization
> 
> ImportError: No module named mice

**Comment by sergeyf** [comment]
Huh, that's pretty odd. What's your Python version?

**Comment by zeeshansayyed** [comment]
It's 2.7.x. I'll update the exact version as soon I get access to my
machine.

**Comment by zeeshansayyed** [comment]
@sergeyf Yes. I already did that. Installing from git worked.

**Comment by sergeyf** [comment]
Thanks for that. We'll fix it at some point.

**Comment by zeeshansayyed** [comment]
Thanks. By the way, my Python version is 2.7.11

**Comment by iskandr** [comment]
Should be working now!

**Comment by erseema** [comment]
@iskandr  .. could you please help me how to install fancyimpute from git

**Comment by a11apurva** [comment]
Hi from where should I run setup to install it and use from anaconda?
